### PR TITLE
Integrate with Burp Suite

### PR DESCRIPTION
**Pull request by jx6f**
This commit allows to run tplmap as Burp Suite Extension.
See "README.md#Burp Suite Plugin".

### CODE REVIEW

**Comment by jx6f** [comment]
@epinna Could you check this PR?
If you don't have Burp Suite Professional edition, I'll take and send screenshots.

**Comment by jx6f** [comment]
I think #1 will be closed by this feature.
Since Burp Suite's spider can be used, The #10 and #12 might also be closed.

**Comment by epinna** [comment]
You're amazing man. I'll try it tonight and merge asap. Cheers mate.

**Comment by jx6f** [comment]
Thank you, I am looking forward to it.

**Pull request merged**
